version: '3'
services:
  #Api
  promocode-factory-api:
    build: src
    container_name: 'promocode-factory-api'
    restart: always
    ports:
      - "8091:80"
    environment:
      - "ConnectionStrings:DefaultConnection=Host=promocode-factory-db;Port=5432;Database=PromoCodeFactory;Username=postgres;Password=147258369"         
    depends_on: 
      - promocode-factory-db
  #Db
  promocode-factory-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-db'
    restart: always 
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_PASSWORD=147258369